version: 2.1

commands:
  install-composer:
    steps:
      - run: |
          sudo apt install -y software-properties-common
          sudo add-apt-repository -y ppa:ondrej/php
          sudo apt-get update
          sudo apt-get install -y php
          curl -s https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

workflows:
  version: 2

  build-push-deploy:
    jobs:
      - build-test-push-test
      - build-test-push-dev

jobs:

  build-test-push-test:
    parallelism: 1
    machine:
      image: ubuntu-1604:202004-01
    resource_class: medium
    steps:
      - run: git config --global core.abbrev 7
      - checkout
      - install-composer
      - run: composer install --ignore-platform-reqs
      - add_ssh_keys
      - run: make stay@test pli || make stay@test b
      - run: make @test TAG=latest-test; make @test b sb t psi

  build-test-push-dev:
    parallelism: 1
    machine:
      image: ubuntu-1604:202004-01
    resource_class: medium
    steps:
      - run: git config --global core.abbrev 7
      - checkout
      - install-composer
      - run: composer install --ignore-platform-reqs
      - add_ssh_keys
      - run: make stay@test pli || make stay@test b
      - run: make @test TAG=latest-test; make @test b sb t psi

  deploy-expo-android:
    parallelism: 1
    docker:
      - image: circleci/node:12
    resource_class: medium
    steps:
      - checkout
      - run: cd wrapper && npm install && npm install --save-dev expo-cli && npx expo login --non-interactive -u $EXPO_CLI_USERNAME && npx expo build:android -t apk
