version: '2.4'

services:

  idilic:
    extends:
      file: base.yml
      service: idilic
    volumes: ['${OUTROOTDIR}/:/app']
    depends_on: [database]
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      DHOST_IP: ${DHOST_IP}

  server:
    extends:
      file: base.yml
      service: server
    volumes:
      - '${OUTROOTDIR}:/app'
    depends_on: [database]
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      DHOST_IP: ${DHOST_IP}

  stream-control:
    ports:
      - "127.0.0.1:8888:8080"
    extends:
      file: base.yml
      service: server
    volumes:
      - '${OUTROOTDIR}:/app'
    depends_on: [database]
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      IDS_DOMAIN: stream-control
      DHOST_IP: ${DHOST_IP}

  database:
    ports: ['${IDS_EXPOSE_SQL:-0}:${IDS_DATABASES_MAIN_PORT:-3306}']
    extends:
      file: base.yml
      service: database

  redis:
    ports:
      - "127.0.0.1:6379:6379"
    extends:
      file: base.yml
      service: redis

  webdis:
    ports:
      - "127.0.0.1:7379:7379"
    extends:
      file: base.yml
      service: webdis

  livestream:
    volumes:
      - ../../tmp/hls:/tmp/hls
    ports:
      - "127.0.0.1:1935:1935"
    extends:
      file: base.yml
      service: livestream

  balancer:
    ports:
      - "8080:8080"
      - "443:443"
      - "80:80"
    extends:
      file: base.yml
      service: balancer

  ytdl:
    extends:
      file: base.yml
      service: ytdl

  brunch:
    ports:
      - "9485:9485"
    extends:
      file: base.yml
      service: brunch

volumes:
  schema:
    driver: local
