version: '2.4'

services:

  idilic:
    extends:
      file: base.yml
      service: idilic
    volumes: ['${OUTROOTDIR}/:/app']
    depends_on: [database]
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      DHOST_IP: ${DHOST_IP}

  server:
    ports: ['${IDS_EXPOSE_HTTP:-0}:8080']
    extends:
      file: base.yml
      service: server
    volumes: ['${OUTROOTDIR}:/app']
    depends_on: [database]
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      DHOST_IP: ${DHOST_IP}

  database:
    ports: ['${IDS_EXPOSE_SQL:-0}:${IDS_DATABASES_MAIN_PORT:-3306}']
    extends:
      file: base.yml
      service: database

  redis:
    extends:
      file: base.yml
      service: redis

  livestream:
    volumes:
      - ../../tmp/hls:/tmp/hls
    ports:
      - "127.0.0.1:1935:1935"
      - "127.0.0.1:8080:8080"
    extends:
      file: base.yml
      service: livestream

  brunch:
    ports:
      - "127.0.0.1:3333:3333"
      - "127.0.0.1:9485:9485"
    extends:
      file: base.yml
      service: brunch

volumes:
  schema:
    driver: local
